import { Jimp } from "jimp";
import { describe, expect, it } from "vitest";
import { normalizeImageToDataUrl, sniffImageFormat } from "../src/image-format.js";

/** A real, valid PNG generated by jimp (avoids hand-rolled base64 mistakes). */
async function makePng(): Promise<Buffer> {
  const img = new Jimp({ width: 4, height: 4, color: 0x00ff00ff });
  return img.getBuffer("image/png");
}

/** A real, valid JPEG generated by jimp. */
async function makeJpeg(): Promise<Buffer> {
  const img = new Jimp({ width: 4, height: 4, color: 0x0000ffff });
  return img.getBuffer("image/jpeg", { quality: 90 });
}

describe("sniffImageFormat", () => {
  it("detects PNG, JPEG, GIF and WebP from magic bytes", async () => {
    const png = await makePng();
    expect(sniffImageFormat(png)).toBe("png");
    const jpeg = await makeJpeg();
    expect(sniffImageFormat(jpeg)).toBe("jpeg");
    expect(sniffImageFormat(Buffer.from("GIF89a....", "utf8"))).toBe("gif");
    const webp = Buffer.concat([Buffer.from("RIFFxxxxWEBP", "utf8"), Buffer.alloc(8)]);
    expect(sniffImageFormat(webp)).toBe("webp");
  });

  it("returns undefined for non-raster / empty input", () => {
    expect(sniffImageFormat(Buffer.from("hello world", "utf8"))).toBeUndefined();
    expect(sniffImageFormat(Buffer.alloc(0))).toBeUndefined();
  });
});

describe("normalizeImageToDataUrl", () => {
  it("passes through an already-valid PNG with a correct data URL", async () => {
    const png = await makePng();
    const res = await normalizeImageToDataUrl(png);
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    expect(res.mime).toBe("image/png");
    expect(res.dataUrl.startsWith("data:image/png;base64,")).toBe(true);
    // Round-trip: the data URL must decode back to a sniffable PNG.
    const decoded = Buffer.from(res.dataUrl.split(",")[1]!, "base64");
    expect(sniffImageFormat(decoded)).toBe("png");
  });

  it("passes through an already-valid JPEG without re-encoding", async () => {
    const jpeg = await makeJpeg();
    const res = await normalizeImageToDataUrl(jpeg);
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    expect(res.mime).toBe("image/jpeg");
    expect(res.dataUrl.startsWith("data:image/jpeg;base64,")).toBe(true);
  });

  it("passes through WebP bytes (accepted by DeepSeek) with image/webp MIME", async () => {
    const webp = Buffer.concat([Buffer.from("RIFFxxxxWEBP", "utf8"), Buffer.alloc(8)]);
    const res = await normalizeImageToDataUrl(webp);
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    expect(res.mime).toBe("image/webp");
    expect(res.dataUrl.startsWith("data:image/webp;base64,")).toBe(true);
  });

  it("rejects garbage bytes with an error instead of shipping them", async () => {
    const res = await normalizeImageToDataUrl(Buffer.from("definitely not an image", "utf8"));
    expect(res.ok).toBe(false);
    if (res.ok) return;
    expect(res.message).toMatch(/not a decodable image|image is empty/);
  });

  it("rejects empty input", async () => {
    const res = await normalizeImageToDataUrl(Buffer.alloc(0));
    expect(res.ok).toBe(false);
  });
});
