export {
  COMPACTION_SUMMARY_MARKER,
  FILES_DROPPED_MARKER_REGEX,
  FILES_DROPPED_TAG,
  buildFilesDroppedMarker,
  isCompactionSummary,
  parseFilesDroppedMarker,
  stripCompactionMarker,
} from "./compaction.js";
export {
  FILE_PATH_TOOLS,
  extractPathsFromArgs,
  isFilePathTool,
} from "./tool-paths.js";
export type { FilePathTool } from "./tool-paths.js";
export { derivePrefix } from "./derive-prefix.js";
export {
  AT_MENTION_PATTERN,
  MAX_IMAGE_BYTES,
  SUPPORTED_IMAGE_EXTENSIONS,
  imageMimeForExtension,
  isSupportedImagePath,
  scanImageMentions,
  stripMentionTokens,
  stripTrailingMentionDots,
} from "./image-attach.js";
export type { ImageMention } from "./image-attach.js";
export { formatBytes } from "./format.js";
export { messageOf } from "./error.js";
export { DAY_MS } from "./time.js";
export {
  GEMINI_MODELS,
  GPT56_MODELS,
  KNOWN_MODELS,
  SUPPORTED_OFFICIAL_MODELS,
  modelAcceptsImages,
} from "./models.js";
export type {
  ConfirmationChoice,
  PlanVerdict,
  CheckpointVerdict,
  RevisionVerdict,
  ChoiceVerdict,
  ReasoningEffort,
  ChoiceOption,
  PlanStep,
} from "./permission-types.js";
export {
  toApprovalPrompt,
  resolveApprovalPrompt,
} from "./approval-prompt.js";
export {
  clipText,
  flattenText,
  redactDiagnosticText,
  redactDiagnosticValue,
  sanitizeFilename,
} from "./text.js";
export type { SanitizeFilenameOptions } from "./text.js";
export type {
  ApprovalPrompt,
  ApprovalAction,
  ApprovalTone,
  ApprovalPromptKind,
} from "./approval-prompt.js";
export type {
  EditMode,
  ExternalSessionApp,
  ExternalSessionSource,
  WebSearchEngineName,
  ReadyEvent,
  ProtocolErrorEvent,
  TurnCompleteEvent,
  DesktopDiagnosticLevel,
  DesktopDiagnosticEvent,
  ConfirmRequiredEvent,
  PathAccessRequiredEvent,
  ChoiceRequiredEvent,
  PlanRequiredEvent,
  CheckpointRequiredEvent,
  RevisionRequiredEvent,
  StepCompletedEvent,
  PlanClearedEvent,
  SessionsEvent,
  SessionImportSourcesEvent,
  SessionImportResultEvent,
  MentionResultsEvent,
  MentionPreviewEvent,
  TabOpenedEvent,
  TabClosedEvent,
  TabsSnapshotEvent,
  McpSpecStatus,
  McpSpecInfo,
  McpSpecsEvent,
  SkillScope,
  SkillInfo,
  SkillsEvent,
  CtxBreakdownEvent,
  MemoryEntryKind,
  MemoryEntryInfo,
  MemoryEntryDetail,
  MemoryEvent,
  MemoryDetailEvent,
  MemoryResultEvent,
  MemoryExportEvent,
  RetryResultEvent,
  BtwResultEvent,
  JobInfo,
  JobsEvent,
  LoadedSegment,
  LoadedMessage,
  SessionLoadedEvent,
  SessionCompactedEvent,
  SessionEmptyEvent,
  NeedsSetupEvent,
  SettingsEvent,
  BalanceInfoItem,
  BalanceEvent,
  CodexQuota,
  CodexQuotaEvent,
  CodexQuotaWindow,
  ModelEndpointInfo,
  OllamaModelsEvent,
  OllamaQuota,
  OllamaQuotaEvent,
  OllamaQuotaWindow,
  SettingsPatch,
  OutgoingCommand,
  UserImageAttachment,
} from "./desktop-protocol.js";
